### ISSUE TITLE
把less文件require进index.js打包，background图片路径导致报错

### ISSUE THREAD

**Issue by Tinker404** [ant-design/antd-bin#13]
怎么解决？

**Comment by sorrycc** [comment]
报错贴出来看下。

**Comment by Tinker404** [comment]
``` css
.login-banner {
  background: url("../../public/img/lb.png") center top no-repeat;
}
```

```
Uncaught Error: Cannot find module "./less/style.main.less"
```
